# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Scan

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
    
jobs:
  build-scan:
    environment: FortifyEnvironment
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write
      
    steps:
    - name: Checkout Solution
      uses: actions/checkout@v4
      with:
        path: MyVSSolution

    - name: Checkout Shared Project
      uses: actions/checkout@v4
      with:
        repository: PedroGarciaOT/MyVSSharedProject
        path: MyVSSharedProject
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      # with:
        # Folder location of where vswhere.exe is located if a self-hosted agent
        # vswhere-path: # optional
        # Version of Visual Studio to search; defaults to latest if not specified
        # vs-version: # optional
        # Enable searching for pre-release versions of Visual Studio/MSBuild
        # vs-prerelease: # optional
        # The preferred processor architecture of MSBuild. Can be either "x86", "x64", or "arm64". "x64" is only available from Visual Studio version 17.0 and later.
        # msbuild-architecture: # optional, default is x86
              
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

#    - name: Restore dependencies
#      run: dotnet restore

    # DotNet Build
#    - name: Build 
#      run: dotnet build --no-restore

    # MSBuild Build
    - name: Build 
      run: msbuild MyVSSolution/MyVSSolution.sln -t:clean -t:restore -t:rebuild
      
 #   - name: Test
 #     run: dotnet test --no-build --verbosity normal

    # Fortify AST Scan
    - name: Scan 
      # You may pin to the exact commit or the version.
      # uses: fortify/github-action@ff40cc3fc263fa6edc64b77fa2486e79a6e32d1b
      uses: fortify/github-action@v1
      with:
        # Run a SAST scan, takes either true or false (default)
        sast-scan: true
        debricked-sca-scan: true
      env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          FOD_RELEASE: ${{vars.FOD_RELEASEID}}          
          PACKAGE_EXTRA_OPTS: -oss -bt msbuild -bf 'MyVSSolution/MyVSSolution.sln'
          DO_PACKAGE_DEBUG: true
          DO_EXPORT: true
          DO_JOB_SUMMARY: true
          DO_PR_COMMENT: true

    - name: Output ScanCentral Log
      if: failure()
        run: |
          echo "=== Begin scancentral.log ==="
          set SC_CLIENT_VERSION=
          type "C:\Users\runneradmin\AppData\Local\Fortify\scancentral-24.4.1\log\scancentral.log" || echo "Log file not found."
          echo "=== End scancentral.log ==="
