name: SCA and SAST

on:
  workflow_dispatch:
    
jobs:
  fod-sast:
    environment: FortifyEnvironment
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write
      
    steps:
    - name: Checkout Solution
      uses: actions/checkout@v4
      with:
        path: MyVSSolution

    - name: Checkout Shared Project
      uses: actions/checkout@v4
      with:
        repository: PedroGarciaOT/MyVSSharedProject
        path: MyVSSharedProject
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
              
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Fortify AST Scan
    - name: SCA 
      uses: fortify/github-action@v1
      with:
        sast-scan: false
        debricked-sca-scan: true
      env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          FOD_RELEASE: ${{vars.FOD_RELEASEID}}
          DO_JOB_SUMMARY: true

    - name: SAST 
      uses: fortify/github-action@v1
      with:
        sast-scan: true
        debricked-sca-scan: false
      env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          FOD_RELEASE: ${{vars.FOD_RELEASEID}}
          DO_JOB_SUMMARY: true
